// Generated by scripts/generate_tool_maps.py. Do not edit manually.

class ToolNavInfo {
  final String country;
  final String section;
  final String label;

  const ToolNavInfo({
    required this.country,
    required this.section,
    required this.label,
  });
}

const Map<String, ToolNavInfo> toolIdMap = {
  'australia_affordability': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'Affordability',
  ),
  'australia_amortization': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'Amortization',
  ),
  'australia_construction_loan': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'Construction Loan',
  ),
  'australia_dti': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'DTI Ratio',
  ),
  'australia_extra_repayments': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'Extra Repayments',
  ),
  'australia_lmi': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'LMI Calculator',
  ),
  'australia_mortgage_calc': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'Mortgage Calc',
  ),
  'australia_offset': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'Offset Account',
  ),
  'australia_refinance_tool': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'Refinance Tool',
  ),
  'australia_stamp_duty': ToolNavInfo(
    country: 'australia',
    section: 'core',
    label: 'Stamp Duty (AUS)',
  ),
  'canada_affordability': ToolNavInfo(
    country: 'canada',
    section: 'core',
    label: 'Affordability',
  ),
  'canada_amortization': ToolNavInfo(
    country: 'canada',
    section: 'core',
    label: 'Amortization',
  ),
  'canada_cmhc': ToolNavInfo(
    country: 'canada',
    section: 'core',
    label: 'CMHC Insurance',
  ),
  'canada_gds_tds': ToolNavInfo(
    country: 'canada',
    section: 'core',
    label: 'GDS / TDS Ratio',
  ),
  'canada_mortgage_calc': ToolNavInfo(
    country: 'canada',
    section: 'core',
    label: 'Mortgage Calc',
  ),
  'canada_prepayment_calc': ToolNavInfo(
    country: 'canada',
    section: 'core',
    label: 'Prepayment Calc',
  ),
  'canada_renewal_planner': ToolNavInfo(
    country: 'canada',
    section: 'core',
    label: 'Renewal Planner',
  ),
  'canada_stress_test': ToolNavInfo(
    country: 'canada',
    section: 'core',
    label: 'Stress Test Calc',
  ),
  'europe_affordability': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Affordability',
  ),
  'europe_amortization': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Amortization',
  ),
  'europe_country_comparison': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Country Comparison',
  ),
  'europe_currency_converter': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Currency Converter',
  ),
  'europe_dti': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'DTI Ratio',
  ),
  'europe_euribor_tracker': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Euribor Tracker',
  ),
  'europe_mortgage_calc': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Mortgage Calc',
  ),
  'europe_non_resident_calc': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Non-Resident Calc',
  ),
  'europe_notary_fee_calc': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Notary Fee Calc',
  ),
  'europe_property_tax_calc': ToolNavInfo(
    country: 'europe',
    section: 'core',
    label: 'Property Tax Calc',
  ),
  'india_core_amortization': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'Amortization',
  ),
  'india_core_balance_transfer': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'Balance Transfer',
  ),
  'india_core_car_loan_emi': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'Car Loan EMI',
  ),
  'india_core_emi_calculator': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'EMI Calculator',
  ),
  'india_core_floating_vs_fixed': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'Floating vs Fixed',
  ),
  'india_core_foir_calculator': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'FOIR Calculator',
  ),
  'india_core_joint_loan_calc': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'Joint Loan Calc',
  ),
  'india_core_loan_eligibility': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'Loan Eligibility',
  ),
  'india_core_prepayment_calc': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'Prepayment Calc',
  ),
  'india_core_under_construction': ToolNavInfo(
    country: 'india',
    section: 'core',
    label: 'Under Construction',
  ),
  'india_govt_capital_gains_tax': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'Capital Gains Tax',
  ),
  'india_govt_cibil_score_impact': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'CIBIL Score Impact',
  ),
  'india_govt_first_home_buyer': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'First Home Buyer',
  ),
  'india_govt_gst_calculator': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'GST Calculator',
  ),
  'india_govt_pmay_subsidy': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'PMAY Subsidy',
  ),
  'india_govt_section_24b': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'Section 24B',
  ),
  'india_govt_section_80c': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'Section 80C',
  ),
  'india_govt_stamp_duty_calc': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'Stamp Duty Calc',
  ),
  'india_govt_tds_on_property': ToolNavInfo(
    country: 'india',
    section: 'govt_schemes',
    label: 'TDS on Property',
  ),
  'india_nri_account': ToolNavInfo(
    country: 'india',
    section: 'nri',
    label: 'NRI Account',
  ),
  'india_nri_fema_compliance': ToolNavInfo(
    country: 'india',
    section: 'nri',
    label: 'FEMA Compliance',
  ),
  'india_nri_home_loan': ToolNavInfo(
    country: 'india',
    section: 'nri',
    label: 'NRI Home Loan',
  ),
  'india_nri_usd_inr_converter': ToolNavInfo(
    country: 'india',
    section: 'nri',
    label: 'USD inr Converter',
  ),
  'india_pf_ai_advisor': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'AI Advisor',
  ),
  'india_pf_education_loan': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'Education Loan',
  ),
  'india_pf_epf_calculator': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'EPF Calculator',
  ),
  'india_pf_gold_loan_calc': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'Gold Loan Calc',
  ),
  'india_pf_income_tax_calc': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'Income Tax Calc',
  ),
  'india_pf_lap_calculator': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'LAP Calculator',
  ),
  'india_pf_nps_calculator': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'NPS Calculator',
  ),
  'india_pf_personal_loan_emi': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'Personal Loan EMI',
  ),
  'india_pf_ppf_calculator': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'PPF Calculator',
  ),
  'india_pf_sip_calculator': ToolNavInfo(
    country: 'india',
    section: 'personal_finance',
    label: 'SIP Calculator',
  ),
  'india_state_all_states': ToolNavInfo(
    country: 'india',
    section: 'state_tools',
    label: 'All States',
  ),
  'india_state_delhi': ToolNavInfo(
    country: 'india',
    section: 'state_tools',
    label: 'Delhi',
  ),
  'india_state_karnataka': ToolNavInfo(
    country: 'india',
    section: 'state_tools',
    label: 'Karnataka',
  ),
  'india_state_maharashtra': ToolNavInfo(
    country: 'india',
    section: 'state_tools',
    label: 'Maharashtra',
  ),
  'india_state_tamil_nadu': ToolNavInfo(
    country: 'india',
    section: 'state_tools',
    label: 'Tamil Nadu',
  ),
  'india_state_telangana': ToolNavInfo(
    country: 'india',
    section: 'state_tools',
    label: 'Telangana',
  ),
  'nz_core_affordability_calc': ToolNavInfo(
    country: 'nz',
    section: 'core',
    label: 'Affordability Calc',
  ),
  'nz_core_amortization': ToolNavInfo(
    country: 'nz',
    section: 'core',
    label: 'Amortization',
  ),
  'nz_core_car_loan_calc': ToolNavInfo(
    country: 'nz',
    section: 'core',
    label: 'Car Loan Calc',
  ),
  'nz_core_dti_calculator': ToolNavInfo(
    country: 'nz',
    section: 'core',
    label: 'DTI Calculator',
  ),
  'nz_core_extra_repayments': ToolNavInfo(
    country: 'nz',
    section: 'core',
    label: 'Extra Repayments',
  ),
  'nz_core_mortgage_calc': ToolNavInfo(
    country: 'nz',
    section: 'core',
    label: 'Mortgage Calc',
  ),
  'nz_core_refixing_calc': ToolNavInfo(
    country: 'nz',
    section: 'core',
    label: 'Refixing Calc',
  ),
  'nz_core_repayment_calc': ToolNavInfo(
    country: 'nz',
    section: 'core',
    label: 'Repayment Calc',
  ),
  'nz_fhb_deposit_calc': ToolNavInfo(
    country: 'nz',
    section: 'first_home',
    label: 'Deposit Calc',
  ),
  'nz_fhb_first_home_buyer': ToolNavInfo(
    country: 'nz',
    section: 'first_home',
    label: 'First Home Buyer',
  ),
  'nz_fhb_preapproval_guide': ToolNavInfo(
    country: 'nz',
    section: 'first_home',
    label: 'Preapproval Guide',
  ),
  'nz_fhb_solicitor_costs': ToolNavInfo(
    country: 'nz',
    section: 'first_home',
    label: 'Solicitor Costs',
  ),
  'nz_kiwisaver_balance': ToolNavInfo(
    country: 'nz',
    section: 'kiwisaver',
    label: 'KiwiSaver Balance',
  ),
  'nz_kiwisaver_calc': ToolNavInfo(
    country: 'nz',
    section: 'kiwisaver',
    label: 'KiwiSaver Calc',
  ),
  'nz_kiwisaver_employer_contrib': ToolNavInfo(
    country: 'nz',
    section: 'kiwisaver',
    label: 'Employer Contrib',
  ),
  'nz_kiwisaver_homestart_grant': ToolNavInfo(
    country: 'nz',
    section: 'kiwisaver',
    label: 'HomeStart Grant',
  ),
  'nz_lvr_band_tool': ToolNavInfo(
    country: 'nz',
    section: 'lvr',
    label: 'LVR Band Tool',
  ),
  'nz_lvr_calculator': ToolNavInfo(
    country: 'nz',
    section: 'lvr',
    label: 'LVR Calculator',
  ),
  'nz_lvr_deposit_builder': ToolNavInfo(
    country: 'nz',
    section: 'lvr',
    label: 'Deposit Builder',
  ),
  'nz_lvr_low_equity_margin': ToolNavInfo(
    country: 'nz',
    section: 'lvr',
    label: 'Low Equity Margin',
  ),
  'nz_pf_budget_planner': ToolNavInfo(
    country: 'nz',
    section: 'personal_finance',
    label: 'Budget Planner',
  ),
  'nz_pf_construction_loan': ToolNavInfo(
    country: 'nz',
    section: 'personal_finance',
    label: 'Construction Loan',
  ),
  'nz_pf_credit_score': ToolNavInfo(
    country: 'nz',
    section: 'personal_finance',
    label: 'Credit Score',
  ),
  'nz_pf_debt_consolidation': ToolNavInfo(
    country: 'nz',
    section: 'personal_finance',
    label: 'Debt Consolidation',
  ),
  'nz_pf_income_tax_calc': ToolNavInfo(
    country: 'nz',
    section: 'personal_finance',
    label: 'Income Tax Calc',
  ),
  'nz_pf_refinance_calc': ToolNavInfo(
    country: 'nz',
    section: 'personal_finance',
    label: 'Refinance Calc',
  ),
  'nz_pf_revolving_credit': ToolNavInfo(
    country: 'nz',
    section: 'personal_finance',
    label: 'Revolving Credit',
  ),
  'nz_tax_bright_line_test': ToolNavInfo(
    country: 'nz',
    section: 'tax_invest',
    label: 'Bright Line Test',
  ),
  'nz_tax_interest_deductibility': ToolNavInfo(
    country: 'nz',
    section: 'tax_invest',
    label: 'Interest Deductibility',
  ),
  'nz_tax_investment_property': ToolNavInfo(
    country: 'nz',
    section: 'tax_invest',
    label: 'Investment Property',
  ),
  'nz_tax_nzx_investor_calc': ToolNavInfo(
    country: 'nz',
    section: 'tax_invest',
    label: 'NZX Investor Calc',
  ),
  'nz_tax_rental_yield_calc': ToolNavInfo(
    country: 'nz',
    section: 'tax_invest',
    label: 'Rental Yield Calc',
  ),
  'nz_tax_ring_fencing_rules': ToolNavInfo(
    country: 'nz',
    section: 'tax_invest',
    label: 'Ring Fencing Rules',
  ),
  'uk_affordability': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'Affordability',
  ),
  'uk_amortization': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'Amortization',
  ),
  'uk_buy_to_let': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'Buy to Let',
  ),
  'uk_help_to_buy': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'Help to Buy',
  ),
  'uk_income_multiples': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'Income Multiples',
  ),
  'uk_ltv_calc': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'LTV Calc',
  ),
  'uk_mortgage_calc': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'Mortgage Calc',
  ),
  'uk_remortgage_tool': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'Remortgage Tool',
  ),
  'uk_sdlt_calculator': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'SDLT Calculator',
  ),
  'uk_stamp_duty_sdlt': ToolNavInfo(
    country: 'uk',
    section: 'core',
    label: 'Stamp Duty (SDLT)',
  ),
  'usa_core_affordability': ToolNavInfo(
    country: 'usa',
    section: 'core',
    label: 'Affordability',
  ),
  'usa_core_amortization': ToolNavInfo(
    country: 'usa',
    section: 'core',
    label: 'Amortization',
  ),
  'usa_core_auto_loan': ToolNavInfo(
    country: 'usa',
    section: 'core',
    label: 'Auto Loan',
  ),
  'usa_core_down_payment': ToolNavInfo(
    country: 'usa',
    section: 'core',
    label: 'Down Payment',
  ),
  'usa_core_dti_calculator': ToolNavInfo(
    country: 'usa',
    section: 'core',
    label: 'DTI Calculator',
  ),
  'usa_core_mortgage_calc': ToolNavInfo(
    country: 'usa',
    section: 'core',
    label: 'Mortgage Calc',
  ),
  'usa_core_piti_calculator': ToolNavInfo(
    country: 'usa',
    section: 'core',
    label: 'PITI Calculator',
  ),
  'usa_core_refinance_calc': ToolNavInfo(
    country: 'usa',
    section: 'core',
    label: 'Refinance Calc',
  ),
  'usa_insctax_closing_costs': ToolNavInfo(
    country: 'usa',
    section: 'insurance_tax',
    label: 'Closing Costs',
  ),
  'usa_insctax_flood_ins': ToolNavInfo(
    country: 'usa',
    section: 'insurance_tax',
    label: 'Flood Insurance',
  ),
  'usa_insctax_hoa_fee_impact': ToolNavInfo(
    country: 'usa',
    section: 'insurance_tax',
    label: 'HOA Fee Impact',
  ),
  'usa_insctax_homeowner_ins': ToolNavInfo(
    country: 'usa',
    section: 'insurance_tax',
    label: 'Homeowner Ins.',
  ),
  'usa_insctax_pmi': ToolNavInfo(
    country: 'usa',
    section: 'insurance_tax',
    label: 'PMI Calculator',
  ),
  'usa_insctax_property_tax': ToolNavInfo(
    country: 'usa',
    section: 'insurance_tax',
    label: 'Property Tax Calc',
  ),
  'usa_invest_1031_exchange': ToolNavInfo(
    country: 'usa',
    section: 'real_estate',
    label: '1031 Exchange',
  ),
  'usa_invest_cash_on_cash': ToolNavInfo(
    country: 'usa',
    section: 'real_estate',
    label: 'Cash-on-Cash Return',
  ),
  'usa_invest_fix_and_flip': ToolNavInfo(
    country: 'usa',
    section: 'real_estate',
    label: 'Fix & Flip Calc',
  ),
  'usa_invest_rental_yield_calc': ToolNavInfo(
    country: 'usa',
    section: 'real_estate',
    label: 'Rental Yield Calc',
  ),
  'usa_loan_arm': ToolNavInfo(
    country: 'usa',
    section: 'loan_programs',
    label: 'ARM Calculator',
  ),
  'usa_loan_construction': ToolNavInfo(
    country: 'usa',
    section: 'loan_programs',
    label: 'Construction Loan',
  ),
  'usa_loan_fha': ToolNavInfo(
    country: 'usa',
    section: 'loan_programs',
    label: 'FHA Loan Calc',
  ),
  'usa_loan_jumbo': ToolNavInfo(
    country: 'usa',
    section: 'loan_programs',
    label: 'Jumbo Loan',
  ),
  'usa_loan_usda': ToolNavInfo(
    country: 'usa',
    section: 'loan_programs',
    label: 'USDA Loan',
  ),
  'usa_loan_va': ToolNavInfo(
    country: 'usa',
    section: 'loan_programs',
    label: 'VA Loan Calc',
  ),
  'usa_pf_credit_score_impact': ToolNavInfo(
    country: 'usa',
    section: 'personal_finance',
    label: 'Credit Score Impact',
  ),
  'usa_pf_debt_payoff_planner': ToolNavInfo(
    country: 'usa',
    section: 'personal_finance',
    label: 'Debt Payoff Planner',
  ),
  'usa_pf_heloc': ToolNavInfo(
    country: 'usa',
    section: 'personal_finance',
    label: 'HELOC Calculator',
  ),
  'usa_pf_home_equity_loan': ToolNavInfo(
    country: 'usa',
    section: 'personal_finance',
    label: 'Home Equity Loan',
  ),
  'usa_pf_moving_cost_calc': ToolNavInfo(
    country: 'usa',
    section: 'personal_finance',
    label: 'Moving Cost Calc',
  ),
  'usa_pf_rent_vs_buy': ToolNavInfo(
    country: 'usa',
    section: 'personal_finance',
    label: 'Rent vs Buy',
  ),
  'usa_pf_student_loan_dti': ToolNavInfo(
    country: 'usa',
    section: 'personal_finance',
    label: 'Student Loan DTI',
  ),
  'usa_pf_tax_deduction_calc': ToolNavInfo(
    country: 'usa',
    section: 'personal_finance',
    label: 'Tax Deduction Calc',
  ),
  'usa_state_all_states': ToolNavInfo(
    country: 'usa',
    section: 'state_tools',
    label: 'All States',
  ),
  'usa_state_california': ToolNavInfo(
    country: 'usa',
    section: 'state_tools',
    label: 'California',
  ),
  'usa_state_florida': ToolNavInfo(
    country: 'usa',
    section: 'state_tools',
    label: 'Florida',
  ),
  'usa_state_illinois': ToolNavInfo(
    country: 'usa',
    section: 'state_tools',
    label: 'Illinois',
  ),
  'usa_state_new_york': ToolNavInfo(
    country: 'usa',
    section: 'state_tools',
    label: 'New York',
  ),
  'usa_state_texas': ToolNavInfo(
    country: 'usa',
    section: 'state_tools',
    label: 'Texas',
  ),
};
